# Netlify Configuration for FlavorStream Studio
[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (build output)
  publish = "build"
  
  # Environment variables for build
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Redirect rules for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Content Security Policy (optional but recommended)
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://generativelanguage.googleapis.com;"

# Error pages
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# API proxy for Gemini AI (if needed)
[[redirects]]
  from = "/api/*"
  to = "https://generativelanguage.googleapis.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Branch-specific settings
[context.production]
  command = "npm run build"
  [context.production.environment]
    REACT_APP_ENVIRONMENT = "production"

[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    REACT_APP_ENVIRONMENT = "preview"

[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    REACT_APP_ENVIRONMENT = "development"
